version: '3.8'
services:
  frontend:
    image: kristianrpo30/frontend:latest
    restart: always
    environment:
      - NEXT_PUBLIC_BASE_URL_API_AUTH=${NEXT_PUBLIC_BASE_URL_API_AUTH}
      - NEXT_PUBLIC_BASE_URL_API_BOOK=${NEXT_PUBLIC_BASE_URL_API_BOOK}
      - NEXT_PUBLIC_BASE_URL_STATIC_SERVER=${NEXT_PUBLIC_BASE_URL_STATIC_SERVER}
    ports:
      - "4000:4000"
    volumes:
      - /mnt/nfs:/mnt/nfs
    networks:
      - default
    deploy:
      replicas: 2 
      restart_policy:
        condition: on-failure

  auth:
    image: kristianrpo30/authentication:latest
    restart: always
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - NFS_MOUNT_POINT=${NFS_MOUNT_POINT}
    ports:
      - "5000:5000"
    volumes:
      - /mnt/nfs:/mnt/nfs
    networks:
      - default
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  book:
    image: kristianrpo30/book:latest
    restart: always
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - NFS_MOUNT_POINT=${NFS_MOUNT_POINT}
    ports:
      - "5001:5001"
    volumes:
      - /mnt/nfs:/mnt/nfs
    networks:
      - default
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  bookstore_net:
    driver: overlay
