version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - NFS_MOUNT_POINT=${NFS_MOUNT_POINT}
    ports:
      - "5000:5000"
    volumes:
      - /mnt/nfs:/mnt/nfs
    networks:
      - bookstore_net

networks:
  bookstore_net: